---
title: "second exercise"
author: "LJH"
date: "2021年3月21日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1.3
### 1
```{r}
score<-factor(c(rep("优",3),rep("良",6),rep("中",18),rep("及格",9),rep("不及格",4)))
par(mfrow=c(1,2))
barplot(table(score))
pie(table(score))
```

### 2
```{r}
data<-c(4.5,1.8,9.3,6.1,8.2,13.9,23.5,3.2,56.8,80.7,4.9,37.2
        ,32.1,4.1,47.5,16.8,3.4,3,33.8,4.3,3.1,1.2,5.7,35)
lambda<-c(-1,-0.5,0,0.5,1)
box.cox<-function(data,lamb){
  if (lamb==0){
    log(data)
  }
  else{
    (data^lamb-1)/lamb
  }
}
par(mfrow=c(2,3))
for (lamb in lambda){
  scatter.smooth(data,box.cox(data,lamb),xlab="Origin",ylab = paste("Box-Cox lambda=",lamb,sep = ""))
}
```

## 1.4
### 1
```{r}
data<-c(35,38,44,33,44,43,48,40,45,30,
        45,32,42,39,49,37,45,37,36,42,
        31,41,45,46,34,30,43,37,44,49,
        36,46,32,36,37,37,45,36,46,42,
        38,43,34,38,47,35,29,41,40,41)
par(mfrow=c(1,2))
hist(data,main="histogram of time span",xlab="time span")
boxplot(data,xlab="time span")
```

### 2
```{r}
data<-data.frame(A=c(38.7,41.5,43.8,44.5,45.5,46.0,47.7,58.0),
                 B=c(39.2,39.3,39.7,41.4,41.8,42.9,43.3,45.8),
                 C=c(34.0,35.0,39.0,40.0,43.0,43.0,44.0,45.0),
                 D=c(34.0,34.8,34.8,35.4,37.2,37.8,41.2,42.8))
boxplot(data)
```

